export const GET_ALL_CHARACTERS_TYPE = "GET_ALL_CHARACTERS_TYPE";
export const SET_TOTAL_PAGES = "SET_TOTAL_PAGES";
export const SET_LOADING_CHARACTERS_TYPE = "SET_LOADING_CHARACTERS_TYPE";
export const FILTER_CHARACTERS_TYPE = "FILTER_CHARACTERS_TYPE";
export const SET_NEW_FILTERS_TYPE = "SET_NEW_FILTERS_TYPE";
export const RESET_ALL_FILTERS_TYPE = "RESET_ALL_FILTERS_TYPE";
export const SET_SELECTED_CHARACTER_TYPE = "SET_SELECTED_CHARACTER_TYPE";