export const GET_ALL_CHARACTERS_TYPE = "GET_ALL_CHARACTERS_TYPE";
export const SET_LOADING_CHARACTERS_TYPE = "SET_LOADING_CHARACTERS_TYPE";
export const GET_CHARACTERS_BY_NAME_TYPE = "GET_ALL_CHARACTERS_BY_NAME_TYPE";
export const SET_SEARCH_BY_NAME = "SET_SEARCH_BY_NAME";
export const FILTER_CHARACTERS_TYPE = "FILTER_CHARACTERS_TYPE";
export const SET_NEW_FILTERS_TYPE = "SET_NEW_FILTERS_TYPE";
export const RESET_ALL_FILTERS_TYPE = "RESET_ALL_FILTERS_TYPE";
export const SET_SELECTED_CHARACTER_TYPE = "SET_SELECTED_CHARACTER_TYPE";
export const CLEAR_SELECTED_CHARACTER = "CLEAR_SELECTED_CHARACTER";

// modal types
export const SET_SHOW_DETAIL_MODAL = "SET_SHOW_DETAIL_MODAL";
export const SET_HIDE_DETAIL_MODAL = "SET_HIDE_DETAIL_MODAL";