export const GET_ALL_CHARACTERS_TYPE = "GET_ALL_CHARACTERS_TYPE";
export const SET_LOADING_CHARACTERS_TYPE = "SET_LOADING_CHARACTERS_TYPE";
export const GET_CHARACTERS_BY_NAME_TYPE = "GET_ALL_CHARACTERS_BY_NAME_TYPE";
export const FILTER_CHARACTERS_BY_STATUS_TYPE = "FILTER_CHARACTERS_BY_STATUS_TYPE";
export const SET_STATUS_FILTER_TYPE = "SET_STATUS_FILTER_TYPE";