export const GET_ALL_CHARACTERS_TYPE = "GET_ALL_CHARACTERS";
export const SET_LOADING_CHARACTERS_TYPE = "SET_LOADING_CHARACTERS";
export const GET_CHARACTERS_BY_NAME_TYPE = "GET_ALL_CHARACTERS_BY_NAME_TYPE";